apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxcart
  labels:
    app: oxcart
    name: oxcart
  namespace: area51
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxcart
      name: oxcart
  template:
    metadata:
      labels:
        app: oxcart
        name: oxcart
    spec:
      containers:
      - resources:
          limits:
            cpu: '0.5'
        image: registry.ocp4.example.com:8443/redhattraining/todo-angular:v1.1
        name: oxcart
        ports:
        - containerPort: 8080
          name: oxcart
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oxcart
    name: oxcart
  name: oxcart
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: oxcart
